const selection = {
  IcoMoonType: 'selection',
  icons: [],
  height: 1024,
  metadata: {
    name: 'icomoon',
  },
  preferences: {
    showGlyphs: true,
    showQuickUse: true,
    showQuickUse2: true,
    showSVGs: true,
    fontPref: {
      prefix: 'icomoon-',
      metadata: {
        fontFamily: 'icomoon-font',
        majorVersion: 1,
        minorVersion: 0,
      },
      metrics: {
        emSize: 1024,
        baseline: 6.25,
        whitespace: 50,
      },
      embed: false,
      ie7: false,
      noie8: true,
      cssVars: true,
      cssVarsFormat: 'scss',
      showSelector: false,
      showMetrics: false,
      showMetadata: false,
      showVersion: false,
      resetPoint: 59648,
    },
    imagePref: {
      prefix: 'icomoon-',
      png: true,
      useClassSelector: true,
      color: 0,
      bgColor: 16777215,
      classSelector: '.icon',
      name: 'icomoon',
    },
    historySize: 50,
    showCodes: false,
    gridSize: 16,
    showLiga: false,
    showGrid: false,
  },
};
module.exports = selection;